#!/bin/sh

#
# Collect system information using hooks, save to file.
#
# (c) 2013 The Matriculation Examination Board of Finland
# http://digabi.fi/
# Author: Ville Korhonen <ville.korhonen@ylioppilastutkinto.fi>
# GPLv3

HOOKS_DIR="/usr/lib/digabi/collect-hooks"
LOGFILE="/var/log/digabi-feedback.log"

if [ ! -w "${LOGFILE}" ]
then
    LOGFILE="${HOME}/digabi-feedback.log"
fi

if [ -f "${LOGFILE}" ]
then
    echo "I: Logfile already exists, will not rewrite => exiting." 1>&2
    exit 1
fi

for s in ${HOOKS_DIR}/*.sh
do
    if [ -x "${s}" ]
    then
        echo "# BEGIN: --$(basename ${s})-- #" >>${LOGFILE}
        ${s} >>${LOGFILE}
        echo "# END:   --$(basename ${s})-- #" >>${LOGFILE}
    fi
done
echo "I: Log saved to ${LOGFILE}." 1>&2

