#!/bin/sh

#
# Collect system information using hooks, save to file.
#
# (c) 2013 The Matriculation Examination Board of Finland
# http://digabi.fi/
# Author: Ville Korhonen <ville.korhonen@ylioppilastutkinto.fi>
# GPLv3
HOOKS_DIR="/usr/lib/digabi/feedback-hooks"

for s in ${HOOKS_DIR}/*.sh
do
    if [ -x "${s}" ]
    then
        echo "# BEGIN: --$(basename ${s})-- #"
        ${s}
        echo "# END:   --$(basename ${s})-- #"
    fi
done